apiVersion: v1
kind: Config

clusters:
  - name: mocked-cluster
    cluster:
      server: https://127.0.0.1:6443
      insecure-skip-tls-verify: true

users:
  - name: mocked-user
    user:
      token: dummy-token-1234567890

contexts:
  - name: mocked-context
    context:
      cluster: mocked-cluster
      user: mocked-user
      namespace: inventory-staging

current-context: mocked-context
